# Generated by Django 4.0.4 on 2022-05-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_owner'),
        ('accounts', '0003_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='orders.order'),
        ),
    ]
