# Generated by Django 4.0.5 on 2022-07-01 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')])),
                ('secondPhoneNumber', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')])),
                ('totalSpend', models.IntegerField(blank=True, default=0)),
                ('reference', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
