# Generated by Django 4.0.4 on 2022-05-23 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='secondPhoneNumber',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{2,3}-\\d{3,4}-\\d{4}$')]),
        ),
    ]
