# Generated by Django 4.0.5 on 2022-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
