# Generated by Django 4.0.5 on 2022-06-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reference',
            field=models.CharField(max_length=200),
        ),
    ]
