# Generated by Django 4.0.5 on 2022-07-01 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='무제', max_length=100)),
                ('introduction', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='<function now at 0x7fcf244d81f0>', max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('worker', models.CharField(default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('weather', models.CharField(blank=True, default='맑음', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='farms.farm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
