# Generated by Django 4.0.4 on 2022-05-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_alter_farm_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='log',
        ),
        migrations.AddField(
            model_name='log',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='farms.farm'),
        ),
    ]
