# Generated by Django 4.0.5 on 2022-07-02 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_log_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 18, 53, 32449)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 0, 18, 53, 32449)),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, default='<function now at 0x7f0159ace1f0>', max_length=255, null=True),
        ),
    ]
