# Generated by Django 4.0.5 on 2022-06-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='log',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='log',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='weather',
            field=models.CharField(blank=True, default='맑음', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='worker',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='introduction',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='title',
            field=models.CharField(default='무제', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, default='<function now at 0x7f2eaf0c9f70>', max_length=255, null=True),
        ),
    ]
