# Generated by Django 4.0.5 on 2022-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_image_log_image_log_note_log_weather_log_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, default='<function now at 0x7f0fc23dfee0>', max_length=255, null=True),
        ),
    ]
