# Generated by Django 4.0.5 on 2022-06-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0013_alter_log_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(blank=True, default='<function now at 0x7f86a9443040>', max_length=255, null=True),
        ),
    ]
