# Generated by Django 4.0.5 on 2022-07-01 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('isPaid', models.CharField(choices=[(True, 'Cash'), (False, 'Card'), ('refund', 'Refund')], default=True, max_length=100)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('customerMemo', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('sellerMemo', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1024)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=1024)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderAddress', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.order')),
                ('product', models.ForeignKey(default='존재하지 않음', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orderItem', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderImages', to='orders.order')),
            ],
        ),
    ]
