# Generated by Django 4.0.4 on 2022-05-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_receiver_alter_order_customermemo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.CharField(blank=True, default=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customers.customer'), max_length=100, null=True),
        ),
    ]
