# Generated by Django 4.0.5 on 2022-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiverPhoneNumber',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
