# Generated by Django 4.0.5 on 2022-07-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_receiverphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('naver', 'Naver'), ('hompageCard', 'HomePageCard')], max_length=100, null=True),
        ),
    ]
