# Generated by Django 4.0.4 on 2022-05-30 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_owner'),
        ('orders', '0007_alter_order_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orderItem', to='products.product'),
        ),
    ]
