# Generated by Django 4.0.4 on 2022-05-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
