# Generated by Django 4.0.5 on 2022-06-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deleveredAt',
            new_name='deliveredAt',
        ),
    ]
