# Generated by Django 4.0.5 on 2022-06-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
        ('orders', '0013_rename_deleveredat_order_deliveredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default='존재하지 않음', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='orderItem', to='products.product'),
        ),
    ]
