# Generated by Django 4.0.5 on 2022-06-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=100, null=True),
        ),
    ]
