# Generated by Django 4.0.5 on 2022-06-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
